const TICKETS_LOADED = 'TICKETS_LOADED'
const TICKETS_REQUESTED = 'TICKETS_REQUESTED'
const TICKETS_ERROR = 'TICKETS_ERROR'
const CHECKBOX_CHANGED = 'CHECKBOX_CHANGED'
const FILTER_CHANGED = 'FILTER_CHANGED'
const TICKETS_TO_SHOW_CHANGED = 'TICKETS_TO_SHOW_CHANGED'

export { TICKETS_LOADED, TICKETS_REQUESTED, TICKETS_ERROR, CHECKBOX_CHANGED, FILTER_CHANGED, TICKETS_TO_SHOW_CHANGED }
